name: Sheets Monitor Hourly Check

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  run_monitor_script:
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout Repository
        uses: actions/checkout@v6

      - name: üêç Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: üõ†Ô∏è Install Dependencies
        run: pip install -r requirements.txt

      - name: üöÄ Run Monitoring Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          STATE_SHEET_ID: ${{ secrets.STATE_SHEET_ID }}
          CLEARS_SHEET_ID: ${{ secrets.CLEARS_SHEET_ID }}
          CLEARS_PAGE_NAME: ${{ secrets.CLEARS_PAGE_NAME }}
        run: python main.py